GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "New Event",
  "description":"This is a New Event",
  "date": "2017-01-01T00:00:00",
  "price": 500
}

###
@eventId = {{ createEvent.response.body.id }}

###
PATCH http://localhost:3000/events/7aaea0ae-7e29-4eaa-bb56-a5659dda5495
Content-Type: application/json

{
  "name": "New Event",
  "description":"This is a New Event",
  "date": "2017-01-01T00:00:00",
  "price": 500
}

###
DELETE http://localhost:3000/events/5e41fba5-a942-4c3e-b13d-a9af41ad0f11
Content-Type: application/json


###
GET http://localhost:3000/events/df379aa4-e3d0-4f5a-ae10-e4a984e7e926/sposts

###
POST http://localhost:3000/events/aa8140aa-5036-406c-b42b-d3f61db04d45/spots
Content-Type: application/json

{
  "name": "A3"
}

###
POST http://localhost:3000/events/aa8140aa-5036-406c-b42b-d3f61db04d45/reserve
Content-Type: application/json

{
  "spots": ["A3"],
  "ticket_kind": "full",
  "email": "test@teste.com"
}